"""Main dashboard (README.md) generation."""

from datetime import UTC, datetime
from pathlib import Path

from improveit_dashboard.models.repository import Repository
from improveit_dashboard.utils.logging import get_logger

logger = get_logger(__name__)


def generate_dashboard(
    repositories: dict[str, Repository],
    output_path: Path,
    tracked_users: list[str],
) -> None:
    """Generate the main README.md dashboard.

    Args:
        repositories: Dict mapping full_name to Repository
        output_path: Path to output README.md
        tracked_users: List of tracked usernames
    """
    logger.info(f"Generating dashboard: {output_path}")

    # Collect stats per user
    user_stats: dict[str, dict[str, int]] = {}
    for user in tracked_users:
        user_stats[user] = {
            "total": 0,
            "draft": 0,
            "open": 0,
            "merged": 0,
            "closed": 0,
        }

    for repo in repositories.values():
        for pr in repo.prs.values():
            if pr.author in user_stats:
                stats = user_stats[pr.author]
                stats["total"] += 1
                stats[pr.status] += 1

    # Generate markdown
    lines = [
        "# ImprovIt Dashboard",
        "",
        "Tracking improveit tool PRs (codespell, shellcheck) across GitHub repositories.",
        "",
        "## Summary",
        "",
        f"*Last updated: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
    ]

    # Overall stats
    total_repos = len(repositories)
    total_prs = sum(len(repo.prs) for repo in repositories.values())
    total_merged = sum(repo.merged_count for repo in repositories.values())
    total_open = sum(repo.open_count for repo in repositories.values())

    lines.extend(
        [
            f"- **Repositories tracked**: {total_repos}",
            f"- **Total PRs**: {total_prs}",
            f"- **Merged**: {total_merged}",
            f"- **Open**: {total_open}",
            "",
        ]
    )

    # Per-user summary table
    lines.extend(
        [
            "## Contributors",
            "",
            "| User | Total | Draft | Open | Merged | Closed |",
            "|------|-------|-------|------|--------|--------|",
        ]
    )

    for user in sorted(tracked_users):
        stats = user_stats.get(user, {"total": 0, "draft": 0, "open": 0, "merged": 0, "closed": 0})

        # Format counts as links if > 0
        def link_count(count: int, status: str, username: str) -> str:
            if count > 0:
                return f"[{count}](READMEs/{username}/{status}.md)"
            return str(count)

        total_link = f"[{stats['total']}](READMEs/{user}.md)" if stats["total"] > 0 else "0"
        draft_link = link_count(stats["draft"], "draft", user)
        open_link = link_count(stats["open"], "open", user)
        merged_link = link_count(stats["merged"], "merged", user)
        closed_link = link_count(stats["closed"], "closed", user)

        lines.append(
            f"| [{user}](https://github.com/{user}) "
            f"| {total_link} "
            f"| {draft_link} "
            f"| {open_link} "
            f"| {merged_link} "
            f"| {closed_link} |"
        )

    lines.append("")

    # Repository behavior summary
    behavior_counts: dict[str, int] = {
        "welcoming": 0,
        "selective": 0,
        "unresponsive": 0,
        "hostile": 0,
        "insufficient_data": 0,
    }
    for repo in repositories.values():
        behavior_counts[repo.behavior_category] += 1

    if any(v > 0 for k, v in behavior_counts.items() if k != "insufficient_data"):
        lines.extend(
            [
                "## Repository Responsiveness",
                "",
                "Based on response times and acceptance rates:",
                "",
                "| Category | Count | Description |",
                "|----------|-------|-------------|",
                f"| Welcoming | {behavior_counts['welcoming']} | Fast response, high acceptance |",
                f"| Selective | {behavior_counts['selective']} | Slower response, moderate acceptance |",
                f"| Unresponsive | {behavior_counts['unresponsive']} | Slow or no response |",
                f"| Hostile | {behavior_counts['hostile']} | Quick rejection |",
                "",
            ]
        )

    # Footer
    lines.extend(
        [
            "---",
            "",
            "*Generated by [improveit-dashboard](https://github.com/yarikoptic/improveit-dashboard)*",
        ]
    )

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")

    logger.info(f"Generated dashboard with {len(tracked_users)} users, {total_prs} PRs")
